# Generated by Django 4.1.1 on 2022-10-01 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TeamLeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_leader_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="WorkTime",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        help_text="Work type either full-time or part-time",
                        max_length=15,
                    ),
                ),
                (
                    "hours",
                    models.IntegerField(
                        help_text="hours per week full-time 40hrs/week"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("team_name", models.CharField(max_length=50)),
                (
                    "team_leader",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.teamleader",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=40)),
                ("hourly_rate", models.IntegerField()),
                (
                    "team",
                    models.OneToOneField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.team",
                    ),
                ),
                (
                    "worktime",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.worktime",
                    ),
                ),
            ],
        ),
    ]
