# Generated by Django 4.1.1 on 2022-10-01 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamleader",
            name="hourly_rate",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teamleader",
            name="worktime",
            field=models.ForeignKey(
                blank=True,
                default=0,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.worktime",
            ),
        ),
    ]
