# Generated by Django 4.1.1 on 2022-10-01 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_teamleader_hourly_rate_teamleader_worktime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamleader",
            name="worktime",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.worktime",
            ),
        ),
    ]
