# Generated by Django 4.1.1 on 2022-10-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_teamleader_worktime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamleader",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
